import type { Metadata } from "next";
import { getSession } from "@/app/api/auth/authOptions";
import AppSessionProvider from "../../providers/appSessionProvider";
import { NotificationProvider } from "@/providers/notificationProvider";
import ScrollToUpButton from "@/components/ScrollToUpButton";
import { LoadingProvider } from "@/providers/loadingProvider";
import "../../globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { DashboardSidebar } from "@/components/DashboardSidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  return (
    <html lang="es">
      <head>
        <title>TecnoVacantesRD</title>
      </head>
      <body className="flex flex-col min-h-screen">
        {/* Barra de navegación */}
        <AppSessionProvider session={session}>
          <LoadingProvider>
            <NotificationProvider>
              <SidebarProvider>
                <DashboardSidebar />
                <main>
                  <SidebarTrigger />
                  {children}
                </main>
              </SidebarProvider>
              <ScrollToUpButton />
            </NotificationProvider>
          </LoadingProvider>
        </AppSessionProvider>
      </body>
    </html>
  );
}
